const tokenTypes = Object.freeze({
    "h1": "h1",
    "h2": "h2",
    "h3": "h3",
    "h4": "h4",
    "h5": "h5",
    "h6": "h6",
    "ul": "ul",
    "sl": "sl",
    "ol": "ol",
    "li": "li",
    "hr": "hr",
    "dash": "-",
    "eoi": "eoi",
    "img": "img",
    "equal": "=",
    "link": "link",
    "string": "string",
    "header": "header",
    "leftbracket": "(",
    "rightbracket": ")",
    "Invalid": "invalid",
    "newline": "newline",
    "leftsquarebracket": "[",
    "rightsquarebracket": "]",
    "blockquote": "blockquote",
});

export default tokenTypes;